apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  # Refresh every 5 minutes
  refreshInterval: 5m
  
  # Reference to the SecretStore
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
    
  # The target Secret that will be created
  target:
    name: grafana-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: "{{ .admin_user | toString }}"
        admin-password: "{{ .admin_password | toString }}"
        
  # Data to fetch from Vault
  data:
    - secretKey: admin_user
      remoteRef:
        key: voicehive/monitoring/grafana
        property: admin_user
    - secretKey: admin_password
      remoteRef:
        key: voicehive/monitoring/grafana
        property: admin_password
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: monitoring
spec:
  provider:
    vault:
      server: "https://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "grafana"
          serviceAccountRef:
            name: "grafana"
---
