# Staging Environment Configuration
# Environment-specific settings for staging deployment

environment:
  name: "staging"
  tier: "staging"
  region: "us-west-2"

# Application Configuration
application:
  name: "voicehive-hotels"
  version: "{{ .Values.image.tag }}"

  # Logging Configuration
  logging:
    level: "DEBUG"
    format: "json"
    structured: true
    correlation_id: true

  # Security Configuration
  security:
    enhanced_mode: true
    audit_logging: true
    pii_redaction: true
    security_headers: true

  # Performance Configuration
  performance:
    connection_pooling: true
    caching_enabled: true
    metrics_collection: true

# Database Configuration
database:
  host: "staging-postgres.voicehive.internal"
  port: 5432
  name: "voicehive_staging"
  ssl_mode: "require"
  connection_pool:
    min_size: 5
    max_size: 20
    timeout: 30

# Redis Configuration
redis:
  host: "staging-redis.voicehive.internal"
  port: 6379
  db: 0
  ssl: true
  connection_pool:
    max_connections: 20
    timeout: 5

# External Services
external_services:
  # PMS Connectors
  pms:
    timeout: 30
    retry_attempts: 3
    circuit_breaker:
      failure_threshold: 5
      timeout: 60

  # TTS Services
  tts:
    azure_speech:
      enabled: true
      timeout: 10
    elevenlabs:
      enabled: true
      timeout: 15

  # ASR Services
  asr:
    riva:
      enabled: true
      timeout: 30
    azure_speech:
      enabled: true
      timeout: 20

# Rate Limiting Configuration
rate_limiting:
  enabled: true
  default_limits:
    requests_per_minute: 100
    requests_per_hour: 2000
    requests_per_day: 20000
  burst_limit: 20

# Authentication Configuration
authentication:
  jwt:
    algorithm: "RS256"
    expiration: 900 # 15 minutes
    refresh_expiration: 86400 # 24 hours
  api_keys:
    enabled: true
    vault_path: "secret/staging/api-keys"

# Monitoring Configuration
monitoring:
  enabled: true
  metrics:
    prometheus:
      enabled: true
      port: 8080
      path: "/metrics"
    business_metrics: true

  alerting:
    enabled: true
    severity_levels: ["critical", "warning", "info"]

  tracing:
    enabled: true
    jaeger:
      endpoint: "http://jaeger-collector.monitoring:14268/api/traces"

# Health Check Configuration
health_checks:
  startup:
    path: "/health/startup"
    initial_delay: 10
    period: 10
    timeout: 5
    failure_threshold: 30

  liveness:
    path: "/health/live"
    initial_delay: 30
    period: 10
    timeout: 5
    failure_threshold: 3

  readiness:
    path: "/health/ready"
    initial_delay: 10
    period: 5
    timeout: 3
    failure_threshold: 2

# Resource Configuration
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Scaling Configuration
scaling:
  replicas: 3
  hpa:
    enabled: true
    min_replicas: 2
    max_replicas: 10
    target_cpu: 70
    target_memory: 80

# Network Configuration
network:
  service:
    type: "ClusterIP"
    ports:
      http: 80
      metrics: 8080

  ingress:
    enabled: true
    class: "nginx"
    tls: true
    annotations:
      nginx.ingress.kubernetes.io/rate-limit: "100"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"

# Security Policies
security_policies:
  network_policies:
    enabled: true
    default_deny: true

  pod_security:
    run_as_non_root: true
    read_only_root_filesystem: true
    drop_capabilities: ["ALL"]

  service_mesh:
    istio:
      enabled: true
      mtls: "STRICT"

# Backup and Recovery
backup:
  enabled: true
  schedule: "0 2 * * *" # Daily at 2 AM
  retention: "7d"

# Feature Flags
feature_flags:
  blue_green_deployment: true
  canary_deployment: false
  a_b_testing: false
  enhanced_security: true
  performance_monitoring: true
